version: "2.4"

volumes:
  redis:

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN
      - ETH_PRIVATE_KEY
      - DISCORD_SERVER

  redis:
    image: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
